In [34]:
import pandas as pd
import os 
import sys
import glob
sys.path.append(os.path.abspath(os.path.join('..')))
from config import DATASETS,ML_MODELS
import joblib
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,roc_auc_score
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

latest csv file

In [104]:
def latest_file():
    file_path = glob.glob(os.path.join(DATASETS,"*.csv"))
    if not file_path:
        return None
    else:
        latest_file = max(file_path,key = os.path.getmtime)
        df = pd.read_csv(latest_file)
        return df

In [105]:
df = latest_file()
df['Churn'].isna().sum()

np.int64(0)

split into x and y

In [106]:
x = df.drop(columns='Churn')

le = LabelEncoder()
y = le.fit_transform(df["Churn"])
y

array([0, 0, 1, ..., 0, 1, 0], shape=(7043,))

Train test split

In [107]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)
x_test

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
437,4376-KFVRS,Male,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),114.05,8468.2
2280,2754-SDJRD,Female,1,No,No,8,Yes,Yes,Fiber optic,No,No,No,Yes,Yes,Yes,Month-to-month,Yes,Credit card (automatic),100.15,908.55
2235,9917-KWRBE,Female,0,Yes,Yes,41,Yes,Yes,DSL,Yes,Yes,Yes,No,Yes,No,One year,Yes,Credit card (automatic),78.35,3211.2
4460,0365-GXEZS,Male,0,Yes,No,18,Yes,No,Fiber optic,No,No,Yes,Yes,No,No,Month-to-month,No,Electronic check,78.20,1468.75
3761,9385-NXKDA,Female,0,Yes,No,72,Yes,Yes,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,Yes,Credit card (automatic),82.65,5919.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5143,5204-HMGYF,Female,0,Yes,Yes,49,Yes,No,DSL,Yes,Yes,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,87.20,4345
4439,9950-MTGYX,Male,0,Yes,Yes,28,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),20.30,487.95
3857,3675-EQOZA,Male,0,No,No,5,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Bank transfer (automatic),20.65,93.55
4758,3646-ITDGM,Female,0,No,No,56,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.70,1051.9
5613,3913-FCUUW,Female,0,Yes,Yes,72,Yes,Yes,DSL,Yes,Yes,Yes,Yes,No,No,Two year,Yes,Bank transfer (automatic),70.45,5165.7

load clean pipeline and clean data

In [108]:
# load pipeline
file_path = os.path.join(ML_MODELS,'Data_cleaning_Pipeline.pkl')
preprocessing = joblib.load(file_path)

In [109]:
# clean data
x_train_pre = preprocessing.transform(x_train)
x_train_clean = pd.DataFrame(x_train_pre,columns=preprocessing.get_feature_names_out())
x_test_pre = preprocessing.transform(x_test)
x_test_clean = pd.DataFrame(x_test_pre,columns=preprocessing.get_feature_names_out())
x_test_clean

,totalcharge__TotalCharges,binary__gender,binary__Partner,binary__Dependents,binary__PhoneService,binary__OnlineSecurity,binary__OnlineBackup,binary__DeviceProtection,binary__TechSupport,binary__StreamingTV,...,nominal__Contract_Month-to-month,nominal__Contract_One year,nominal__Contract_Two year,nominal__PaymentMethod_Bank transfer (automatic),nominal__PaymentMethod_Credit card (automatic),nominal__PaymentMethod_Electronic check,nominal__PaymentMethod_Mailed check,fixed__SeniorCitizen,numeric_col__tenure,numeric_col__MonthlyCharges
0,2.731119,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.613701,1.638143
1,-0.606314,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,-0.992402,1.176164
2,0.410260,0.0,1.0,1.0,1.0,2.0,2.0,2.0,0.0,2.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.351370,0.451620
3,-0.358997,1.0,1.0,0.0,1.0,0.0,0.0,2.0,2.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.585198,0.446635
4,1.605853,0.0,1.0,0.0,1.0,2.0,2.0,2.0,0.0,2.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.613701,0.594535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1404,0.910809,0.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.677133,0.745758
1405,-0.792000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.177995,-1.477726
1406,-0.966120,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.114563,-1.466094
1407,-0.543028,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.962175,-1.497668
1408,1.273132,0.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.613701,0.189056

Machine learning models

In [41]:
lr = LogisticRegression(penalty='l2',max_iter=1000,solver='lbfgs',class_weight='balanced')
lr.fit(x_train_clean,y_train)

c:\Users\hamen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

LogisticRegression(class_weight='balanced', max_iter=1000, penalty='l2')

In [42]:
lr_test_pr = lr.predict(x_test_clean)
lr_train_pr = lr.predict(x_train_clean)
lr_test_pr

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

In [43]:
print(classification_report(y_test,lr_test_pr))
print(classification_report(y_train,lr_train_pr))

              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.79      0.62       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

              precision    recall  f1-score   support

           0       0.91      0.73      0.81      4139
           1       0.52      0.81      0.63      1495

    accuracy                           0.75      5634
   macro avg       0.72      0.77      0.72      5634
weighted avg       0.81      0.75      0.77      5634

In [44]:
print(confusion_matrix(y_test,lr_test_pr))

[[747 288]
 [ 80 294]]

In [45]:
cross_val_score(lr,x_train_clean,y_train).mean()

c:\Users\hamen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\hamen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\hamen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\hamen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\hamen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

np.float64(0.7520353789828541)

Random forest

In [46]:
rf = RandomForestClassifier(n_estimators=5000,max_depth=10,min_samples_split=4,max_features='sqrt',class_weight='balanced',random_state=60)
rf.fit(x_train_clean,y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_split=4, n_estimators=5000, random_state=60)

In [47]:
rf_test_pr = rf.predict(x_test_clean)
rf_train_pr = rf.predict(x_train_clean)
rf_test_pr

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

In [48]:
print(classification_report(y_test,rf_test_pr))
print(classification_report(y_train,rf_train_pr))

              precision    recall  f1-score   support

           0       0.88      0.79      0.84      1035
           1       0.55      0.71      0.62       374

    accuracy                           0.77      1409
   macro avg       0.72      0.75      0.73      1409
weighted avg       0.79      0.77      0.78      1409

              precision    recall  f1-score   support

           0       0.96      0.85      0.90      4139
           1       0.69      0.91      0.78      1495

    accuracy                           0.87      5634
   macro avg       0.82      0.88      0.84      5634
weighted avg       0.89      0.87      0.87      5634

In [49]:
print(confusion_matrix(y_test,rf_test_pr))

[[821 214]
 [110 264]]

In [51]:
cross_val_score(rf,x_train_clean,y_train,cv=5).mean()

KeyboardInterrupt:

xgboost

In [52]:
# Define model
xb = XGBClassifier(
    n_estimators=5000,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.4,
    colsample_bytree=0.8,
    random_state=50
)

In [53]:
xb.fit(x_train_clean,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=5000,
              n_jobs=None, num_parallel_tree=None, ...)

In [54]:
y_test_pred = xb.predict(x_test_clean)
y_train_pred = xb.predict(x_train_clean)
print(classification_report(y_test,y_test_pred))
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.84      0.87      0.85      1035
           1       0.60      0.53      0.57       374

    accuracy                           0.78      1409
   macro avg       0.72      0.70      0.71      1409
weighted avg       0.78      0.78      0.78      1409

              precision    recall  f1-score   support

           0       0.93      0.96      0.94      4139
           1       0.87      0.80      0.83      1495

    accuracy                           0.92      5634
   macro avg       0.90      0.88      0.89      5634
weighted avg       0.91      0.92      0.91      5634

In [55]:
print(confusion_matrix(y_test,y_test_pred))

[[902 133]
 [174 200]]

catboost

In [91]:
# define catboost classifier model
catboost = CatBoostClassifier(iterations=5000,
learning_rate=0.05,
depth=2,
l2_leaf_reg =3,
random_state=42)

In [92]:
catboost.fit(x_train_clean,y_train)

0:	learn: 0.6652241	total: 4.28ms	remaining: 21.4s
1:	learn: 0.6394576	total: 7.86ms	remaining: 19.6s
2:	learn: 0.6175039	total: 12.1ms	remaining: 20.1s
3:	learn: 0.5977897	total: 16.1ms	remaining: 20.2s
4:	learn: 0.5840276	total: 20ms	remaining: 20s
5:	learn: 0.5691022	total: 24ms	remaining: 19.9s
6:	learn: 0.5574548	total: 27.7ms	remaining: 19.7s
7:	learn: 0.5469606	total: 31.2ms	remaining: 19.4s
8:	learn: 0.5353283	total: 34.5ms	remaining: 19.1s
9:	learn: 0.5264349	total: 38.2ms	remaining: 19s
10:	learn: 0.5186289	total: 41.9ms	remaining: 19s
11:	learn: 0.5103733	total: 45.9ms	remaining: 19.1s
12:	learn: 0.5026793	total: 51.2ms	remaining: 19.6s
13:	learn: 0.4972920	total: 55.8ms	remaining: 19.9s
14:	learn: 0.4920029	total: 59.6ms	remaining: 19.8s
15:	learn: 0.4875491	total: 63.8ms	remaining: 19.9s
16:	learn: 0.4823434	total: 68.1ms	remaining: 20s
17:	learn: 0.4767894	total: 71.9ms	remaining: 19.9s
18:	learn: 0.4731950	total: 75.8ms	remaining: 19.9s
19:	learn: 0.4689031	total: 79.6ms	remaining: 19.8s
20:	learn: 0.4658906	total: 83.7ms	remaining: 19.8s
21:	learn: 0.4631978	total: 87.2ms	remaining: 19.7s
22:	learn: 0.4599665	total: 91.1ms	remaining: 19.7s
23:	learn: 0.4577423	total: 95.2ms	remaining: 19.7s
24:	learn: 0.4558221	total: 100ms	remaining: 20s
25:	learn: 0.4527654	total: 104ms	remaining: 20s
26:	learn: 0.4508609	total: 109ms	remaining: 20.1s
27:	learn: 0.4494015	total: 113ms	remaining: 20s
28:	learn: 0.4472769	total: 116ms	remaining: 19.9s
29:	learn: 0.4456484	total: 120ms	remaining: 19.9s
30:	learn: 0.4437165	total: 123ms	remaining: 19.8s
31:	learn: 0.4423984	total: 127ms	remaining: 19.6s
32:	learn: 0.4411254	total: 130ms	remaining: 19.6s
33:	learn: 0.4399968	total: 133ms	remaining: 19.5s
34:	learn: 0.4390884	total: 138ms	remaining: 19.5s
35:	learn: 0.4380579	total: 141ms	remaining: 19.4s
36:	learn: 0.4368900	total: 144ms	remaining: 19.3s
37:	learn: 0.4356740	total: 147ms	remaining: 19.2s
38:	learn: 0.4340619	total: 151ms	remaining: 19.2s
39:	learn: 0.4332132	total: 154ms	remaining: 19.1s
40:	learn: 0.4322277	total: 158ms	remaining: 19.1s
41:	learn: 0.4318079	total: 161ms	remaining: 19.1s
42:	learn: 0.4313514	total: 165ms	remaining: 19s
43:	learn: 0.4306392	total: 168ms	remaining: 19s
44:	learn: 0.4297972	total: 171ms	remaining: 18.9s
45:	learn: 0.4294288	total: 175ms	remaining: 18.8s
46:	learn: 0.4287900	total: 178ms	remaining: 18.8s
47:	learn: 0.4282749	total: 182ms	remaining: 18.8s
48:	learn: 0.4278309	total: 186ms	remaining: 18.8s
49:	learn: 0.4271223	total: 189ms	remaining: 18.7s
50:	learn: 0.4264479	total: 192ms	remaining: 18.7s
51:	learn: 0.4258882	total: 196ms	remaining: 18.7s
52:	learn: 0.4254310	total: 200ms	remaining: 18.6s
53:	learn: 0.4250122	total: 204ms	remaining: 18.7s
54:	learn: 0.4247042	total: 208ms	remaining: 18.7s
55:	learn: 0.4239076	total: 213ms	remaining: 18.8s
56:	learn: 0.4233395	total: 217ms	remaining: 18.8s
57:	learn: 0.4228900	total: 221ms	remaining: 18.8s
58:	learn: 0.4224287	total: 224ms	remaining: 18.8s
59:	learn: 0.4220844	total: 228ms	remaining: 18.8s
60:	learn: 0.4217437	total: 233ms	remaining: 18.8s
61:	learn: 0.4214016	total: 237ms	remaining: 18.9s
62:	learn: 0.4209908	total: 240ms	remaining: 18.8s
63:	learn: 0.4202312	total: 244ms	remaining: 18.8s
64:	learn: 0.4200459	total: 247ms	remaining: 18.8s
65:	learn: 0.4194798	total: 251ms	remaining: 18.8s
66:	learn: 0.4189029	total: 255ms	remaining: 18.8s
67:	learn: 0.4185092	total: 259ms	remaining: 18.8s
68:	learn: 0.4182741	total: 263ms	remaining: 18.8s
69:	learn: 0.4180276	total: 266ms	remaining: 18.7s
70:	learn: 0.4177096	total: 269ms	remaining: 18.7s
71:	learn: 0.4172104	total: 273ms	remaining: 18.7s
72:	learn: 0.4170235	total: 277ms	remaining: 18.7s
73:	learn: 0.4166660	total: 280ms	remaining: 18.6s
74:	learn: 0.4164051	total: 283ms	remaining: 18.6s
75:	learn: 0.4161379	total: 287ms	remaining: 18.6s
76:	learn: 0.4159020	total: 290ms	remaining: 18.5s
77:	learn: 0.4157919	total: 293ms	remaining: 18.5s
78:	learn: 0.4155435	total: 296ms	remaining: 18.5s
79:	learn: 0.4152849	total: 299ms	remaining: 18.4s
80:	learn: 0.4149752	total: 303ms	remaining: 18.4s
81:	learn: 0.4145403	total: 306ms	remaining: 18.3s
82:	learn: 0.4144452	total: 309ms	remaining: 18.3s
83:	learn: 0.4143580	total: 312ms	remaining: 18.3s
84:	learn: 0.4139478	total: 315ms	remaining: 18.2s
85:	learn: 0.4137935	total: 319ms	remaining: 18.2s
86:	learn: 0.4135649	total: 322ms	remaining: 18.2s
87:	learn: 0.4133894	total: 325ms	remaining: 18.2s
88:	learn: 0.4132804	total: 329ms	remaining: 18.2s
89:	learn: 0.4129697	total: 333ms	remaining: 18.2s
90:	learn: 0.4127270	total: 336ms	remaining: 18.1s
91:	learn: 0.4125268	total: 340ms	remaining: 18.1s
92:	learn: 0.4123474	total: 343ms	remaining: 18.1s
93:	learn: 0.4121384	total: 346ms	remaining: 18.1s
94:	learn: 0.4118663	total: 350ms	remaining: 18.1s
95:	learn: 0.4117416	total: 353ms	remaining: 18s
96:	learn: 0.4115687	total: 357ms	remaining: 18s
97:	learn: 0.4114031	total: 360ms	remaining: 18s
98:	learn: 0.4111739	total: 363ms	remaining: 18s
99:	learn: 0.4110447	total: 366ms	remaining: 18s
100:	learn: 0.4108901	total: 369ms	remaining: 17.9s
101:	learn: 0.4108143	total: 373ms	remaining: 17.9s
102:	learn: 0.4107548	total: 377ms	remaining: 17.9s
103:	learn: 0.4106618	total: 380ms	remaining: 17.9s
104:	learn: 0.4105907	total: 383ms	remaining: 17.9s
105:	learn: 0.4104710	total: 388ms	remaining: 17.9s
106:	learn: 0.4102631	total: 391ms	remaining: 17.9s
107:	learn: 0.4101557	total: 395ms	remaining: 17.9s
108:	learn: 0.4099656	total: 398ms	remaining: 17.9s
109:	learn: 0.4098448	total: 403ms	remaining: 17.9s
110:	learn: 0.4097890	total: 406ms	remaining: 17.9s
111:	learn: 0.4095676	total: 410ms	remaining: 17.9s
112:	learn: 0.4094420	total: 415ms	remaining: 17.9s
113:	learn: 0.4093208	total: 420ms	remaining: 18s
114:	learn: 0.4092482	total: 423ms	remaining: 18s
115:	learn: 0.4091479	total: 427ms	remaining: 18s
116:	learn: 0.4090059	total: 431ms	remaining: 18s
117:	learn: 0.4089449	total: 434ms	remaining: 18s
118:	learn: 0.4087571	total: 438ms	remaining: 18s
119:	learn: 0.4086185	total: 442ms	remaining: 18s
120:	learn: 0.4085694	total: 446ms	remaining: 18s
121:	learn: 0.4084087	total: 449ms	remaining: 18s
122:	learn: 0.4083044	total: 452ms	remaining: 17.9s
123:	learn: 0.4082077	total: 456ms	remaining: 17.9s
124:	learn: 0.4081141	total: 459ms	remaining: 17.9s
125:	learn: 0.4080664	total: 463ms	remaining: 17.9s
126:	learn: 0.4080134	total: 466ms	remaining: 17.9s
127:	learn: 0.4079417	total: 470ms	remaining: 17.9s
128:	learn: 0.4078693	total: 475ms	remaining: 17.9s
129:	learn: 0.4077564	total: 479ms	remaining: 17.9s
130:	learn: 0.4076815	total: 482ms	remaining: 17.9s
131:	learn: 0.4075957	total: 486ms	remaining: 17.9s
132:	learn: 0.4075328	total: 489ms	remaining: 17.9s
133:	learn: 0.4075076	total: 493ms	remaining: 17.9s
134:	learn: 0.4074429	total: 496ms	remaining: 17.9s
135:	learn: 0.4073855	total: 499ms	remaining: 17.9s
136:	learn: 0.4073289	total: 502ms	remaining: 17.8s
137:	learn: 0.4072608	total: 505ms	remaining: 17.8s
138:	learn: 0.4071959	total: 509ms	remaining: 17.8s
139:	learn: 0.4071154	total: 512ms	remaining: 17.8s
140:	learn: 0.4070291	total: 515ms	remaining: 17.8s
141:	learn: 0.4069648	total: 518ms	remaining: 17.7s
142:	learn: 0.4068046	total: 522ms	remaining: 17.7s
143:	learn: 0.4066346	total: 526ms	remaining: 17.7s
144:	learn: 0.4065417	total: 529ms	remaining: 17.7s
145:	learn: 0.4065072	total: 532ms	remaining: 17.7s
146:	learn: 0.4064595	total: 535ms	remaining: 17.7s
147:	learn: 0.4063565	total: 539ms	remaining: 17.7s
148:	learn: 0.4062282	total: 542ms	remaining: 17.7s
149:	learn: 0.4061478	total: 545ms	remaining: 17.6s
150:	learn: 0.4060938	total: 549ms	remaining: 17.6s
151:	learn: 0.4059953	total: 551ms	remaining: 17.6s
152:	learn: 0.4059599	total: 555ms	remaining: 17.6s
153:	learn: 0.4059315	total: 558ms	remaining: 17.6s
154:	learn: 0.4058606	total: 561ms	remaining: 17.5s
155:	learn: 0.4057855	total: 564ms	remaining: 17.5s
156:	learn: 0.4057103	total: 567ms	remaining: 17.5s
157:	learn: 0.4056662	total: 571ms	remaining: 17.5s
158:	learn: 0.4055818	total: 574ms	remaining: 17.5s
159:	learn: 0.4055058	total: 578ms	remaining: 17.5s
160:	learn: 0.4054800	total: 581ms	remaining: 17.5s
161:	learn: 0.4054333	total: 586ms	remaining: 17.5s
162:	learn: 0.4053730	total: 589ms	remaining: 17.5s
163:	learn: 0.4053320	total: 593ms	remaining: 17.5s
164:	learn: 0.4052841	total: 597ms	remaining: 17.5s
165:	learn: 0.4052525	total: 601ms	remaining: 17.5s
166:	learn: 0.4051638	total: 604ms	remaining: 17.5s
167:	learn: 0.4050840	total: 607ms	remaining: 17.5s
168:	learn: 0.4050288	total: 610ms	remaining: 17.4s
169:	learn: 0.4049561	total: 614ms	remaining: 17.5s
170:	learn: 0.4048273	total: 617ms	remaining: 17.4s
171:	learn: 0.4047750	total: 621ms	remaining: 17.4s
172:	learn: 0.4047092	total: 624ms	remaining: 17.4s
173:	learn: 0.4046269	total: 628ms	remaining: 17.4s
174:	learn: 0.4045358	total: 631ms	remaining: 17.4s
175:	learn: 0.4045113	total: 634ms	remaining: 17.4s
176:	learn: 0.4044297	total: 637ms	remaining: 17.4s
177:	learn: 0.4043529	total: 641ms	remaining: 17.4s
178:	learn: 0.4042864	total: 644ms	remaining: 17.3s
179:	learn: 0.4042149	total: 647ms	remaining: 17.3s
180:	learn: 0.4041440	total: 650ms	remaining: 17.3s
181:	learn: 0.4040729	total: 654ms	remaining: 17.3s
182:	learn: 0.4040213	total: 657ms	remaining: 17.3s
183:	learn: 0.4039590	total: 661ms	remaining: 17.3s
184:	learn: 0.4038673	total: 664ms	remaining: 17.3s
185:	learn: 0.4037429	total: 668ms	remaining: 17.3s
186:	learn: 0.4037116	total: 671ms	remaining: 17.3s
187:	learn: 0.4036355	total: 675ms	remaining: 17.3s
188:	learn: 0.4035091	total: 678ms	remaining: 17.3s
189:	learn: 0.4034502	total: 682ms	remaining: 17.3s
190:	learn: 0.4033131	total: 685ms	remaining: 17.3s
191:	learn: 0.4032431	total: 689ms	remaining: 17.2s
192:	learn: 0.4031697	total: 692ms	remaining: 17.2s
193:	learn: 0.4031157	total: 695ms	remaining: 17.2s
194:	learn: 0.4029954	total: 699ms	remaining: 17.2s
195:	learn: 0.4029428	total: 702ms	remaining: 17.2s
196:	learn: 0.4028765	total: 706ms	remaining: 17.2s
197:	learn: 0.4028032	total: 709ms	remaining: 17.2s
198:	learn: 0.4026834	total: 713ms	remaining: 17.2s
199:	learn: 0.4026143	total: 717ms	remaining: 17.2s
200:	learn: 0.4025544	total: 721ms	remaining: 17.2s
201:	learn: 0.4025007	total: 724ms	remaining: 17.2s
202:	learn: 0.4024538	total: 728ms	remaining: 17.2s
203:	learn: 0.4024109	total: 732ms	remaining: 17.2s
204:	learn: 0.4023046	total: 736ms	remaining: 17.2s
205:	learn: 0.4022601	total: 739ms	remaining: 17.2s
206:	learn: 0.4021640	total: 742ms	remaining: 17.2s
207:	learn: 0.4021241	total: 746ms	remaining: 17.2s
208:	learn: 0.4020379	total: 749ms	remaining: 17.2s
209:	learn: 0.4019665	total: 752ms	remaining: 17.2s
210:	learn: 0.4019297	total: 756ms	remaining: 17.1s
211:	learn: 0.4018819	total: 760ms	remaining: 17.2s
212:	learn: 0.4018205	total: 763ms	remaining: 17.1s
213:	learn: 0.4017625	total: 767ms	remaining: 17.1s
214:	learn: 0.4017034	total: 770ms	remaining: 17.1s
215:	learn: 0.4016458	total: 774ms	remaining: 17.1s
216:	learn: 0.4016040	total: 777ms	remaining: 17.1s
217:	learn: 0.4015647	total: 781ms	remaining: 17.1s
218:	learn: 0.4015127	total: 785ms	remaining: 17.1s
219:	learn: 0.4014157	total: 790ms	remaining: 17.2s
220:	learn: 0.4013790	total: 793ms	remaining: 17.1s
221:	learn: 0.4013162	total: 798ms	remaining: 17.2s
222:	learn: 0.4012193	total: 801ms	remaining: 17.2s
223:	learn: 0.4011823	total: 805ms	remaining: 17.2s
224:	learn: 0.4011399	total: 808ms	remaining: 17.2s
225:	learn: 0.4011022	total: 813ms	remaining: 17.2s
226:	learn: 0.4010423	total: 817ms	remaining: 17.2s
227:	learn: 0.4009557	total: 821ms	remaining: 17.2s
228:	learn: 0.4009042	total: 824ms	remaining: 17.2s
229:	learn: 0.4008670	total: 827ms	remaining: 17.2s
230:	learn: 0.4008208	total: 831ms	remaining: 17.2s
231:	learn: 0.4007724	total: 835ms	remaining: 17.2s
232:	learn: 0.4007365	total: 839ms	remaining: 17.2s
233:	learn: 0.4006757	total: 843ms	remaining: 17.2s
234:	learn: 0.4006031	total: 846ms	remaining: 17.2s
235:	learn: 0.4005562	total: 850ms	remaining: 17.2s
236:	learn: 0.4004782	total: 853ms	remaining: 17.1s
237:	learn: 0.4004232	total: 857ms	remaining: 17.1s
238:	learn: 0.4003371	total: 861ms	remaining: 17.1s
239:	learn: 0.4002712	total: 864ms	remaining: 17.1s
240:	learn: 0.4002177	total: 867ms	remaining: 17.1s
241:	learn: 0.4001752	total: 870ms	remaining: 17.1s
242:	learn: 0.4001445	total: 874ms	remaining: 17.1s
243:	learn: 0.4000758	total: 877ms	remaining: 17.1s
244:	learn: 0.4000331	total: 881ms	remaining: 17.1s
245:	learn: 0.4000051	total: 885ms	remaining: 17.1s
246:	learn: 0.3999776	total: 889ms	remaining: 17.1s
247:	learn: 0.3999275	total: 893ms	remaining: 17.1s
248:	learn: 0.3998851	total: 899ms	remaining: 17.1s
249:	learn: 0.3998252	total: 903ms	remaining: 17.2s
250:	learn: 0.3997563	total: 907ms	remaining: 17.2s
251:	learn: 0.3997184	total: 911ms	remaining: 17.2s
252:	learn: 0.3996473	total: 915ms	remaining: 17.2s
253:	learn: 0.3996022	total: 919ms	remaining: 17.2s
254:	learn: 0.3995710	total: 922ms	remaining: 17.2s
255:	learn: 0.3995265	total: 926ms	remaining: 17.2s
256:	learn: 0.3994662	total: 929ms	remaining: 17.1s
257:	learn: 0.3994240	total: 933ms	remaining: 17.1s
258:	learn: 0.3993765	total: 936ms	remaining: 17.1s
259:	learn: 0.3993156	total: 939ms	remaining: 17.1s
260:	learn: 0.3992518	total: 943ms	remaining: 17.1s
261:	learn: 0.3992209	total: 946ms	remaining: 17.1s
262:	learn: 0.3991916	total: 950ms	remaining: 17.1s
263:	learn: 0.3991376	total: 953ms	remaining: 17.1s
264:	learn: 0.3990928	total: 957ms	remaining: 17.1s
265:	learn: 0.3990594	total: 961ms	remaining: 17.1s
266:	learn: 0.3990200	total: 965ms	remaining: 17.1s
267:	learn: 0.3989922	total: 968ms	remaining: 17.1s
268:	learn: 0.3989566	total: 972ms	remaining: 17.1s
269:	learn: 0.3989040	total: 975ms	remaining: 17.1s
270:	learn: 0.3988649	total: 979ms	remaining: 17.1s
271:	learn: 0.3988083	total: 982ms	remaining: 17.1s
272:	learn: 0.3987778	total: 986ms	remaining: 17.1s
273:	learn: 0.3987148	total: 990ms	remaining: 17.1s
274:	learn: 0.3986883	total: 994ms	remaining: 17.1s
275:	learn: 0.3986406	total: 997ms	remaining: 17.1s
276:	learn: 0.3986024	total: 1s	remaining: 17.1s
277:	learn: 0.3985644	total: 1s	remaining: 17.1s
278:	learn: 0.3985211	total: 1.01s	remaining: 17.1s
279:	learn: 0.3984877	total: 1.01s	remaining: 17.1s
280:	learn: 0.3984588	total: 1.02s	remaining: 17.1s
281:	learn: 0.3984193	total: 1.02s	remaining: 17.1s
282:	learn: 0.3983829	total: 1.02s	remaining: 17.1s
283:	learn: 0.3983499	total: 1.03s	remaining: 17.1s
284:	learn: 0.3983144	total: 1.03s	remaining: 17.1s
285:	learn: 0.3982723	total: 1.03s	remaining: 17s
286:	learn: 0.3982448	total: 1.04s	remaining: 17s
287:	learn: 0.3982201	total: 1.04s	remaining: 17s
288:	learn: 0.3981831	total: 1.04s	remaining: 17s
289:	learn: 0.3981552	total: 1.05s	remaining: 17s
290:	learn: 0.3981302	total: 1.05s	remaining: 17s
291:	learn: 0.3980681	total: 1.05s	remaining: 17s
292:	learn: 0.3980425	total: 1.06s	remaining: 17s
293:	learn: 0.3980060	total: 1.06s	remaining: 17s
294:	learn: 0.3979629	total: 1.06s	remaining: 17s
295:	learn: 0.3979222	total: 1.07s	remaining: 17s
296:	learn: 0.3978505	total: 1.07s	remaining: 17s
297:	learn: 0.3978158	total: 1.07s	remaining: 17s
298:	learn: 0.3977841	total: 1.08s	remaining: 16.9s
299:	learn: 0.3977596	total: 1.08s	remaining: 16.9s
300:	learn: 0.3977219	total: 1.08s	remaining: 16.9s
301:	learn: 0.3976897	total: 1.09s	remaining: 16.9s
302:	learn: 0.3976661	total: 1.09s	remaining: 16.9s
303:	learn: 0.3976426	total: 1.09s	remaining: 16.9s
304:	learn: 0.3975566	total: 1.1s	remaining: 16.9s
305:	learn: 0.3975265	total: 1.1s	remaining: 16.9s
306:	learn: 0.3975043	total: 1.11s	remaining: 16.9s
307:	learn: 0.3974574	total: 1.11s	remaining: 16.9s
308:	learn: 0.3974343	total: 1.11s	remaining: 16.9s
309:	learn: 0.3974057	total: 1.12s	remaining: 16.9s
310:	learn: 0.3973683	total: 1.12s	remaining: 16.9s
311:	learn: 0.3973203	total: 1.12s	remaining: 16.9s
312:	learn: 0.3972435	total: 1.13s	remaining: 16.9s
313:	learn: 0.3971904	total: 1.13s	remaining: 16.9s
314:	learn: 0.3971560	total: 1.13s	remaining: 16.8s
315:	learn: 0.3970981	total: 1.14s	remaining: 16.8s
316:	learn: 0.3970478	total: 1.14s	remaining: 16.8s
317:	learn: 0.3970230	total: 1.14s	remaining: 16.8s
318:	learn: 0.3969933	total: 1.15s	remaining: 16.8s
319:	learn: 0.3969565	total: 1.15s	remaining: 16.8s
320:	learn: 0.3968386	total: 1.15s	remaining: 16.8s
321:	learn: 0.3968162	total: 1.16s	remaining: 16.8s
322:	learn: 0.3967549	total: 1.16s	remaining: 16.8s
323:	learn: 0.3967130	total: 1.16s	remaining: 16.8s
324:	learn: 0.3966691	total: 1.17s	remaining: 16.8s
325:	learn: 0.3966491	total: 1.17s	remaining: 16.8s
326:	learn: 0.3966398	total: 1.18s	remaining: 16.8s
327:	learn: 0.3965871	total: 1.18s	remaining: 16.8s
328:	learn: 0.3965665	total: 1.18s	remaining: 16.8s
329:	learn: 0.3964650	total: 1.19s	remaining: 16.8s
330:	learn: 0.3964406	total: 1.19s	remaining: 16.8s
331:	learn: 0.3964199	total: 1.19s	remaining: 16.8s
332:	learn: 0.3963510	total: 1.2s	remaining: 16.8s
333:	learn: 0.3963283	total: 1.2s	remaining: 16.8s
334:	learn: 0.3962830	total: 1.2s	remaining: 16.8s
335:	learn: 0.3962210	total: 1.21s	remaining: 16.8s
336:	learn: 0.3961563	total: 1.21s	remaining: 16.8s
337:	learn: 0.3961039	total: 1.21s	remaining: 16.8s
338:	learn: 0.3960543	total: 1.22s	remaining: 16.8s
339:	learn: 0.3959820	total: 1.22s	remaining: 16.7s
340:	learn: 0.3959466	total: 1.22s	remaining: 16.7s
341:	learn: 0.3959135	total: 1.23s	remaining: 16.7s
342:	learn: 0.3958540	total: 1.23s	remaining: 16.7s
343:	learn: 0.3958037	total: 1.24s	remaining: 16.7s
344:	learn: 0.3957407	total: 1.24s	remaining: 16.7s
345:	learn: 0.3957089	total: 1.24s	remaining: 16.7s
346:	learn: 0.3956998	total: 1.25s	remaining: 16.7s
347:	learn: 0.3956659	total: 1.25s	remaining: 16.7s
348:	learn: 0.3956218	total: 1.25s	remaining: 16.7s
349:	learn: 0.3956135	total: 1.26s	remaining: 16.7s
350:	learn: 0.3955948	total: 1.26s	remaining: 16.7s
351:	learn: 0.3955392	total: 1.26s	remaining: 16.7s
352:	learn: 0.3955177	total: 1.27s	remaining: 16.7s
353:	learn: 0.3954526	total: 1.27s	remaining: 16.7s
354:	learn: 0.3954118	total: 1.27s	remaining: 16.7s
355:	learn: 0.3953829	total: 1.28s	remaining: 16.7s
356:	learn: 0.3953553	total: 1.28s	remaining: 16.7s
357:	learn: 0.3953106	total: 1.28s	remaining: 16.6s
358:	learn: 0.3952240	total: 1.29s	remaining: 16.6s
359:	learn: 0.3952032	total: 1.29s	remaining: 16.6s
360:	learn: 0.3951705	total: 1.29s	remaining: 16.6s
361:	learn: 0.3950913	total: 1.3s	remaining: 16.6s
362:	learn: 0.3950044	total: 1.3s	remaining: 16.6s
363:	learn: 0.3949586	total: 1.3s	remaining: 16.6s
364:	learn: 0.3949392	total: 1.31s	remaining: 16.6s
365:	learn: 0.3949054	total: 1.31s	remaining: 16.6s
366:	learn: 0.3948624	total: 1.32s	remaining: 16.6s
367:	learn: 0.3948448	total: 1.32s	remaining: 16.6s
368:	learn: 0.3947950	total: 1.32s	remaining: 16.6s
369:	learn: 0.3947754	total: 1.33s	remaining: 16.6s
370:	learn: 0.3947410	total: 1.33s	remaining: 16.6s
371:	learn: 0.3946939	total: 1.33s	remaining: 16.6s
372:	learn: 0.3946349	total: 1.34s	remaining: 16.6s
373:	learn: 0.3946089	total: 1.34s	remaining: 16.6s
374:	learn: 0.3945461	total: 1.34s	remaining: 16.6s
375:	learn: 0.3944900	total: 1.35s	remaining: 16.6s
376:	learn: 0.3944595	total: 1.35s	remaining: 16.6s
377:	learn: 0.3943876	total: 1.36s	remaining: 16.6s
378:	learn: 0.3943434	total: 1.36s	remaining: 16.6s
379:	learn: 0.3943131	total: 1.36s	remaining: 16.6s
380:	learn: 0.3942595	total: 1.37s	remaining: 16.6s
381:	learn: 0.3941941	total: 1.37s	remaining: 16.6s
382:	learn: 0.3941771	total: 1.38s	remaining: 16.6s
383:	learn: 0.3941224	total: 1.38s	remaining: 16.6s
384:	learn: 0.3940678	total: 1.38s	remaining: 16.6s
385:	learn: 0.3940375	total: 1.39s	remaining: 16.6s
386:	learn: 0.3939971	total: 1.39s	remaining: 16.6s
387:	learn: 0.3939729	total: 1.4s	remaining: 16.6s

CatBoostClassifier(depth=2, iterations=5000, l2_leaf_reg=3, learning_rate=0.05, random_state=42)

In [93]:
ct_test_pred = catboost.predict(x_test_clean)
ct_train_pred = catboost.predict(x_train_clean)

In [94]:
ct_train_pred

array([0, 0, 0, ..., 1, 0, 0], shape=(5634,))

In [95]:
print("Test classification Report : \n",classification_report(y_test,ct_test_pred))
print("Train classification Report : \n",classification_report(y_train,ct_train_pred))

Test classification Report :
               precision    recall  f1-score   support

           0       0.84      0.90      0.87      1035
           1       0.66      0.53      0.59       374

    accuracy                           0.80      1409
   macro avg       0.75      0.71      0.73      1409
weighted avg       0.79      0.80      0.79      1409

Train classification Report :
               precision    recall  f1-score   support

           0       0.87      0.93      0.90      4139
           1       0.75      0.61      0.67      1495

    accuracy                           0.84      5634
   macro avg       0.81      0.77      0.79      5634
weighted avg       0.84      0.84      0.84      5634

In [96]:
print(confusion_matrix(y_test,ct_test_pred))

[[932 103]
 [176 198]]

In [61]:
cross_val_score(catboost,x_train_clean,y_train,cv=3).mean()

0:	learn: 0.6651778	total: 3.02ms	remaining: 15.1s
1:	learn: 0.6388757	total: 6.93ms	remaining: 17.3s
2:	learn: 0.6189279	total: 10.6ms	remaining: 17.7s
3:	learn: 0.6001162	total: 14.5ms	remaining: 18.1s
4:	learn: 0.5833010	total: 17.3ms	remaining: 17.3s
5:	learn: 0.5692126	total: 20.5ms	remaining: 17.1s
6:	learn: 0.5547862	total: 23.4ms	remaining: 16.7s
7:	learn: 0.5422597	total: 26.3ms	remaining: 16.4s
8:	learn: 0.5335743	total: 30.6ms	remaining: 17s
9:	learn: 0.5257651	total: 34.3ms	remaining: 17.1s
10:	learn: 0.5188140	total: 37.8ms	remaining: 17.2s
11:	learn: 0.5102052	total: 41.4ms	remaining: 17.2s
12:	learn: 0.5048482	total: 44.7ms	remaining: 17.1s
13:	learn: 0.4990382	total: 47.6ms	remaining: 17s
14:	learn: 0.4933291	total: 50.9ms	remaining: 16.9s
15:	learn: 0.4888583	total: 54ms	remaining: 16.8s
16:	learn: 0.4854420	total: 57.2ms	remaining: 16.8s
17:	learn: 0.4817983	total: 61.1ms	remaining: 16.9s
18:	learn: 0.4783694	total: 64.4ms	remaining: 16.9s
19:	learn: 0.4749595	total: 67.6ms	remaining: 16.8s
20:	learn: 0.4719413	total: 70.4ms	remaining: 16.7s
21:	learn: 0.4694953	total: 73.4ms	remaining: 16.6s
22:	learn: 0.4663532	total: 76.7ms	remaining: 16.6s
23:	learn: 0.4642485	total: 80ms	remaining: 16.6s
24:	learn: 0.4621564	total: 84.2ms	remaining: 16.8s
25:	learn: 0.4603244	total: 87.7ms	remaining: 16.8s
26:	learn: 0.4587477	total: 90.6ms	remaining: 16.7s
27:	learn: 0.4569488	total: 93.7ms	remaining: 16.6s
28:	learn: 0.4552011	total: 96.5ms	remaining: 16.5s
29:	learn: 0.4533146	total: 99.2ms	remaining: 16.4s
30:	learn: 0.4518715	total: 102ms	remaining: 16.4s
31:	learn: 0.4504184	total: 105ms	remaining: 16.3s
32:	learn: 0.4490626	total: 108ms	remaining: 16.2s
33:	learn: 0.4476196	total: 112ms	remaining: 16.4s
34:	learn: 0.4459493	total: 116ms	remaining: 16.5s
35:	learn: 0.4449245	total: 119ms	remaining: 16.4s
36:	learn: 0.4434740	total: 122ms	remaining: 16.4s
37:	learn: 0.4428096	total: 126ms	remaining: 16.4s
38:	learn: 0.4414789	total: 128ms	remaining: 16.3s
39:	learn: 0.4408640	total: 131ms	remaining: 16.3s
40:	learn: 0.4400390	total: 134ms	remaining: 16.2s
41:	learn: 0.4392689	total: 137ms	remaining: 16.2s
42:	learn: 0.4386081	total: 140ms	remaining: 16.2s
43:	learn: 0.4370639	total: 143ms	remaining: 16.1s
44:	learn: 0.4365362	total: 146ms	remaining: 16.1s
45:	learn: 0.4358088	total: 149ms	remaining: 16s
46:	learn: 0.4347771	total: 151ms	remaining: 16s
47:	learn: 0.4342888	total: 155ms	remaining: 15.9s
48:	learn: 0.4340605	total: 157ms	remaining: 15.9s
49:	learn: 0.4332866	total: 160ms	remaining: 15.9s
50:	learn: 0.4326630	total: 163ms	remaining: 15.8s
51:	learn: 0.4322845	total: 166ms	remaining: 15.8s
52:	learn: 0.4313919	total: 169ms	remaining: 15.8s
53:	learn: 0.4303807	total: 172ms	remaining: 15.7s
54:	learn: 0.4299565	total: 175ms	remaining: 15.7s
55:	learn: 0.4296215	total: 178ms	remaining: 15.7s
56:	learn: 0.4290835	total: 180ms	remaining: 15.6s
57:	learn: 0.4285939	total: 184ms	remaining: 15.7s
58:	learn: 0.4283207	total: 187ms	remaining: 15.6s
59:	learn: 0.4277372	total: 191ms	remaining: 15.7s
60:	learn: 0.4274121	total: 194ms	remaining: 15.7s
61:	learn: 0.4271260	total: 199ms	remaining: 15.8s
62:	learn: 0.4267683	total: 202ms	remaining: 15.8s
63:	learn: 0.4263815	total: 206ms	remaining: 15.9s
64:	learn: 0.4260272	total: 208ms	remaining: 15.8s
65:	learn: 0.4259128	total: 211ms	remaining: 15.8s
66:	learn: 0.4255966	total: 214ms	remaining: 15.8s
67:	learn: 0.4252878	total: 217ms	remaining: 15.7s
68:	learn: 0.4249601	total: 220ms	remaining: 15.7s
69:	learn: 0.4245898	total: 222ms	remaining: 15.7s
70:	learn: 0.4242231	total: 225ms	remaining: 15.6s
71:	learn: 0.4237693	total: 228ms	remaining: 15.6s
72:	learn: 0.4235148	total: 231ms	remaining: 15.6s
73:	learn: 0.4231242	total: 233ms	remaining: 15.5s
74:	learn: 0.4229112	total: 237ms	remaining: 15.5s
75:	learn: 0.4225613	total: 239ms	remaining: 15.5s
76:	learn: 0.4219306	total: 242ms	remaining: 15.5s
77:	learn: 0.4216617	total: 245ms	remaining: 15.5s
78:	learn: 0.4213751	total: 248ms	remaining: 15.4s
79:	learn: 0.4211873	total: 251ms	remaining: 15.4s
80:	learn: 0.4207838	total: 254ms	remaining: 15.4s
81:	learn: 0.4204787	total: 257ms	remaining: 15.4s
82:	learn: 0.4201469	total: 261ms	remaining: 15.4s
83:	learn: 0.4198364	total: 264ms	remaining: 15.4s
84:	learn: 0.4195148	total: 267ms	remaining: 15.4s
85:	learn: 0.4192371	total: 269ms	remaining: 15.4s
86:	learn: 0.4190040	total: 274ms	remaining: 15.4s
87:	learn: 0.4189145	total: 276ms	remaining: 15.4s
88:	learn: 0.4186626	total: 279ms	remaining: 15.4s
89:	learn: 0.4184416	total: 283ms	remaining: 15.4s
90:	learn: 0.4183117	total: 285ms	remaining: 15.4s
91:	learn: 0.4180790	total: 289ms	remaining: 15.4s
92:	learn: 0.4176813	total: 292ms	remaining: 15.4s
93:	learn: 0.4176237	total: 295ms	remaining: 15.4s
94:	learn: 0.4173325	total: 298ms	remaining: 15.4s
95:	learn: 0.4171826	total: 302ms	remaining: 15.4s
96:	learn: 0.4170821	total: 305ms	remaining: 15.4s
97:	learn: 0.4169381	total: 309ms	remaining: 15.4s
98:	learn: 0.4168309	total: 312ms	remaining: 15.4s
99:	learn: 0.4166648	total: 315ms	remaining: 15.4s
100:	learn: 0.4165501	total: 318ms	remaining: 15.4s
101:	learn: 0.4163534	total: 321ms	remaining: 15.4s
102:	learn: 0.4162080	total: 324ms	remaining: 15.4s
103:	learn: 0.4161199	total: 327ms	remaining: 15.4s
104:	learn: 0.4159113	total: 330ms	remaining: 15.4s
105:	learn: 0.4157539	total: 333ms	remaining: 15.4s
106:	learn: 0.4155573	total: 336ms	remaining: 15.4s
107:	learn: 0.4152361	total: 339ms	remaining: 15.4s
108:	learn: 0.4151553	total: 342ms	remaining: 15.3s
109:	learn: 0.4150443	total: 345ms	remaining: 15.3s
110:	learn: 0.4149681	total: 348ms	remaining: 15.3s
111:	learn: 0.4148754	total: 350ms	remaining: 15.3s
112:	learn: 0.4147826	total: 353ms	remaining: 15.3s
113:	learn: 0.4147366	total: 356ms	remaining: 15.3s
114:	learn: 0.4145044	total: 359ms	remaining: 15.3s
115:	learn: 0.4144169	total: 363ms	remaining: 15.3s
116:	learn: 0.4143317	total: 365ms	remaining: 15.2s
117:	learn: 0.4142371	total: 368ms	remaining: 15.2s
118:	learn: 0.4140800	total: 371ms	remaining: 15.2s
119:	learn: 0.4139803	total: 376ms	remaining: 15.3s
120:	learn: 0.4138200	total: 379ms	remaining: 15.3s
121:	learn: 0.4136869	total: 383ms	remaining: 15.3s
122:	learn: 0.4135960	total: 386ms	remaining: 15.3s
123:	learn: 0.4134567	total: 389ms	remaining: 15.3s
124:	learn: 0.4133246	total: 392ms	remaining: 15.3s
125:	learn: 0.4131924	total: 395ms	remaining: 15.3s
126:	learn: 0.4131056	total: 399ms	remaining: 15.3s
127:	learn: 0.4130313	total: 402ms	remaining: 15.3s
128:	learn: 0.4128751	total: 405ms	remaining: 15.3s
129:	learn: 0.4127813	total: 408ms	remaining: 15.3s
130:	learn: 0.4126538	total: 411ms	remaining: 15.3s
131:	learn: 0.4125890	total: 414ms	remaining: 15.3s
132:	learn: 0.4125346	total: 417ms	remaining: 15.2s
133:	learn: 0.4124579	total: 419ms	remaining: 15.2s
134:	learn: 0.4122004	total: 423ms	remaining: 15.2s
135:	learn: 0.4121537	total: 426ms	remaining: 15.2s
136:	learn: 0.4120313	total: 429ms	remaining: 15.2s
137:	learn: 0.4118804	total: 432ms	remaining: 15.2s
138:	learn: 0.4116685	total: 434ms	remaining: 15.2s
139:	learn: 0.4115981	total: 438ms	remaining: 15.2s
140:	learn: 0.4115179	total: 440ms	remaining: 15.2s
141:	learn: 0.4114078	total: 443ms	remaining: 15.2s
142:	learn: 0.4113304	total: 446ms	remaining: 15.1s
143:	learn: 0.4111656	total: 449ms	remaining: 15.1s
144:	learn: 0.4110989	total: 453ms	remaining: 15.2s
145:	learn: 0.4109881	total: 457ms	remaining: 15.2s
146:	learn: 0.4109225	total: 460ms	remaining: 15.2s
147:	learn: 0.4107337	total: 463ms	remaining: 15.2s
148:	learn: 0.4106676	total: 467ms	remaining: 15.2s
149:	learn: 0.4105776	total: 470ms	remaining: 15.2s
150:	learn: 0.4104816	total: 474ms	remaining: 15.2s
151:	learn: 0.4103581	total: 477ms	remaining: 15.2s
152:	learn: 0.4102859	total: 480ms	remaining: 15.2s
153:	learn: 0.4100450	total: 484ms	remaining: 15.2s
154:	learn: 0.4099833	total: 487ms	remaining: 15.2s
155:	learn: 0.4099528	total: 490ms	remaining: 15.2s
156:	learn: 0.4098444	total: 493ms	remaining: 15.2s
157:	learn: 0.4097848	total: 496ms	remaining: 15.2s
158:	learn: 0.4097199	total: 499ms	remaining: 15.2s
159:	learn: 0.4096647	total: 501ms	remaining: 15.2s
160:	learn: 0.4095708	total: 504ms	remaining: 15.1s
161:	learn: 0.4095485	total: 507ms	remaining: 15.1s
162:	learn: 0.4094812	total: 511ms	remaining: 15.2s
163:	learn: 0.4093910	total: 513ms	remaining: 15.1s
164:	learn: 0.4093592	total: 516ms	remaining: 15.1s
165:	learn: 0.4093001	total: 519ms	remaining: 15.1s
166:	learn: 0.4092233	total: 522ms	remaining: 15.1s
167:	learn: 0.4091704	total: 525ms	remaining: 15.1s
168:	learn: 0.4090940	total: 528ms	remaining: 15.1s
169:	learn: 0.4090074	total: 530ms	remaining: 15.1s
170:	learn: 0.4089095	total: 533ms	remaining: 15.1s
171:	learn: 0.4087495	total: 536ms	remaining: 15.1s
172:	learn: 0.4087007	total: 539ms	remaining: 15.1s
173:	learn: 0.4086165	total: 542ms	remaining: 15s
174:	learn: 0.4085483	total: 545ms	remaining: 15s
175:	learn: 0.4084579	total: 548ms	remaining: 15s
176:	learn: 0.4083542	total: 550ms	remaining: 15s
177:	learn: 0.4082953	total: 553ms	remaining: 15s
178:	learn: 0.4081927	total: 556ms	remaining: 15s
179:	learn: 0.4080999	total: 559ms	remaining: 15s
180:	learn: 0.4080285	total: 562ms	remaining: 15s
181:	learn: 0.4079412	total: 566ms	remaining: 15s
182:	learn: 0.4078250	total: 570ms	remaining: 15s
183:	learn: 0.4076807	total: 573ms	remaining: 15s
184:	learn: 0.4075784	total: 578ms	remaining: 15s
185:	learn: 0.4075160	total: 582ms	remaining: 15.1s
186:	learn: 0.4074160	total: 587ms	remaining: 15.1s
187:	learn: 0.4073610	total: 591ms	remaining: 15.1s
188:	learn: 0.4072675	total: 595ms	remaining: 15.1s
189:	learn: 0.4072176	total: 599ms	remaining: 15.2s
190:	learn: 0.4071302	total: 602ms	remaining: 15.2s
191:	learn: 0.4070127	total: 605ms	remaining: 15.2s
192:	learn: 0.4069173	total: 609ms	remaining: 15.2s
193:	learn: 0.4068550	total: 612ms	remaining: 15.2s
194:	learn: 0.4067979	total: 616ms	remaining: 15.2s
195:	learn: 0.4067140	total: 620ms	remaining: 15.2s
196:	learn: 0.4066310	total: 623ms	remaining: 15.2s
197:	learn: 0.4065565	total: 627ms	remaining: 15.2s
198:	learn: 0.4064898	total: 631ms	remaining: 15.2s
199:	learn: 0.4063757	total: 634ms	remaining: 15.2s
200:	learn: 0.4063203	total: 637ms	remaining: 15.2s
201:	learn: 0.4061904	total: 643ms	remaining: 15.3s
202:	learn: 0.4061365	total: 647ms	remaining: 15.3s
203:	learn: 0.4060631	total: 652ms	remaining: 15.3s
204:	learn: 0.4060071	total: 657ms	remaining: 15.4s
205:	learn: 0.4058793	total: 661ms	remaining: 15.4s
206:	learn: 0.4058300	total: 666ms	remaining: 15.4s
207:	learn: 0.4057784	total: 669ms	remaining: 15.4s
208:	learn: 0.4057308	total: 674ms	remaining: 15.5s
209:	learn: 0.4056335	total: 679ms	remaining: 15.5s
210:	learn: 0.4055780	total: 683ms	remaining: 15.5s
211:	learn: 0.4055150	total: 687ms	remaining: 15.5s
212:	learn: 0.4054655	total: 690ms	remaining: 15.5s
213:	learn: 0.4054038	total: 694ms	remaining: 15.5s
214:	learn: 0.4053478	total: 699ms	remaining: 15.6s
215:	learn: 0.4053040	total: 706ms	remaining: 15.6s
216:	learn: 0.4052405	total: 710ms	remaining: 15.6s
217:	learn: 0.4051743	total: 713ms	remaining: 15.6s
218:	learn: 0.4050486	total: 718ms	remaining: 15.7s
219:	learn: 0.4050092	total: 722ms	remaining: 15.7s
220:	learn: 0.4048669	total: 727ms	remaining: 15.7s
221:	learn: 0.4047848	total: 730ms	remaining: 15.7s
222:	learn: 0.4047153	total: 734ms	remaining: 15.7s
223:	learn: 0.4046593	total: 738ms	remaining: 15.7s
224:	learn: 0.4045967	total: 742ms	remaining: 15.7s
225:	learn: 0.4045045	total: 746ms	remaining: 15.8s
226:	learn: 0.4044468	total: 755ms	remaining: 15.9s
227:	learn: 0.4043753	total: 761ms	remaining: 15.9s
228:	learn: 0.4042529	total: 767ms	remaining: 16s
229:	learn: 0.4041476	total: 772ms	remaining: 16s
230:	learn: 0.4040845	total: 777ms	remaining: 16s
231:	learn: 0.4040320	total: 784ms	remaining: 16.1s
232:	learn: 0.4039980	total: 790ms	remaining: 16.2s
233:	learn: 0.4039164	total: 794ms	remaining: 16.2s
234:	learn: 0.4038332	total: 800ms	remaining: 16.2s
235:	learn: 0.4037569	total: 806ms	remaining: 16.3s
236:	learn: 0.4036742	total: 809ms	remaining: 16.3s
237:	learn: 0.4036450	total: 814ms	remaining: 16.3s
238:	learn: 0.4035843	total: 818ms	remaining: 16.3s
239:	learn: 0.4035679	total: 824ms	remaining: 16.3s
240:	learn: 0.4035131	total: 830ms	remaining: 16.4s
241:	learn: 0.4034672	total: 834ms	remaining: 16.4s
242:	learn: 0.4033885	total: 837ms	remaining: 16.4s
243:	learn: 0.4033206	total: 842ms	remaining: 16.4s
244:	learn: 0.4032252	total: 846ms	remaining: 16.4s
245:	learn: 0.4031699	total: 851ms	remaining: 16.5s
246:	learn: 0.4031235	total: 859ms	remaining: 16.5s
247:	learn: 0.4030706	total: 863ms	remaining: 16.5s
248:	learn: 0.4030413	total: 867ms	remaining: 16.5s
249:	learn: 0.4029754	total: 872ms	remaining: 16.6s
250:	learn: 0.4028903	total: 877ms	remaining: 16.6s
251:	learn: 0.4028126	total: 882ms	remaining: 16.6s
252:	learn: 0.4026910	total: 887ms	remaining: 16.6s
253:	learn: 0.4026493	total: 890ms	remaining: 16.6s
254:	learn: 0.4025811	total: 895ms	remaining: 16.7s
255:	learn: 0.4025094	total: 899ms	remaining: 16.7s
256:	learn: 0.4024519	total: 903ms	remaining: 16.7s
257:	learn: 0.4023904	total: 906ms	remaining: 16.7s
258:	learn: 0.4023018	total: 911ms	remaining: 16.7s
259:	learn: 0.4022606	total: 914ms	remaining: 16.7s
260:	learn: 0.4022111	total: 918ms	remaining: 16.7s
261:	learn: 0.4021736	total: 921ms	remaining: 16.7s
262:	learn: 0.4021455	total: 925ms	remaining: 16.7s
263:	learn: 0.4020809	total: 928ms	remaining: 16.6s
264:	learn: 0.4020300	total: 932ms	remaining: 16.7s
265:	learn: 0.4019892	total: 936ms	remaining: 16.6s
266:	learn: 0.4019503	total: 940ms	remaining: 16.7s
267:	learn: 0.4019246	total: 945ms	remaining: 16.7s
268:	learn: 0.4018438	total: 950ms	remaining: 16.7s
269:	learn: 0.4018048	total: 954ms	remaining: 16.7s
270:	learn: 0.4017679	total: 958ms	remaining: 16.7s
271:	learn: 0.4017109	total: 961ms	remaining: 16.7s
272:	learn: 0.4016541	total: 965ms	remaining: 16.7s
273:	learn: 0.4016113	total: 968ms	remaining: 16.7s
274:	learn: 0.4015379	total: 972ms	remaining: 16.7s
275:	learn: 0.4014432	total: 975ms	remaining: 16.7s
276:	learn: 0.4013344	total: 979ms	remaining: 16.7s
277:	learn: 0.4012874	total: 982ms	remaining: 16.7s
278:	learn: 0.4012624	total: 986ms	remaining: 16.7s
279:	learn: 0.4011541	total: 989ms	remaining: 16.7s
280:	learn: 0.4010936	total: 993ms	remaining: 16.7s
281:	learn: 0.4010324	total: 997ms	remaining: 16.7s
282:	learn: 0.4009930	total: 1s	remaining: 16.7s
283:	learn: 0.4009137	total: 1.01s	remaining: 16.8s
284:	learn: 0.4008803	total: 1.01s	remaining: 16.8s
285:	learn: 0.4008128	total: 1.02s	remaining: 16.8s
286:	learn: 0.4007372	total: 1.02s	remaining: 16.8s
287:	learn: 0.4006403	total: 1.02s	remaining: 16.8s
288:	learn: 0.4005523	total: 1.03s	remaining: 16.8s
289:	learn: 0.4005380	total: 1.03s	remaining: 16.8s
290:	learn: 0.4004694	total: 1.04s	remaining: 16.8s
291:	learn: 0.4004243	total: 1.04s	remaining: 16.8s
292:	learn: 0.4003873	total: 1.04s	remaining: 16.8s
293:	learn: 0.4002833	total: 1.05s	remaining: 16.8s
294:	learn: 0.4002177	total: 1.05s	remaining: 16.8s
295:	learn: 0.4001569	total: 1.06s	remaining: 16.8s
296:	learn: 0.4001113	total: 1.06s	remaining: 16.8s
297:	learn: 0.4000769	total: 1.07s	remaining: 16.8s
298:	learn: 0.4000366	total: 1.07s	remaining: 16.8s
299:	learn: 0.3999978	total: 1.07s	remaining: 16.9s
300:	learn: 0.3999667	total: 1.08s	remaining: 16.9s
301:	learn: 0.3999121	total: 1.09s	remaining: 16.9s
302:	learn: 0.3998481	total: 1.09s	remaining: 16.9s
303:	learn: 0.3997870	total: 1.1s	remaining: 16.9s
304:	learn: 0.3997348	total: 1.1s	remaining: 16.9s
305:	learn: 0.3996529	total: 1.11s	remaining: 17s
306:	learn: 0.3996177	total: 1.11s	remaining: 17s
307:	learn: 0.3995405	total: 1.11s	remaining: 17s
308:	learn: 0.3994886	total: 1.12s	remaining: 17s
309:	learn: 0.3994278	total: 1.12s	remaining: 17s
310:	learn: 0.3993879	total: 1.13s	remaining: 17s
311:	learn: 0.3993576	total: 1.13s	remaining: 17s
312:	learn: 0.3993128	total: 1.14s	remaining: 17s
313:	learn: 0.3992776	total: 1.14s	remaining: 17s
314:	learn: 0.3992077	total: 1.14s	remaining: 17s
315:	learn: 0.3991796	total: 1.15s	remaining: 17s
316:	learn: 0.3991106	total: 1.15s	remaining: 17s
317:	learn: 0.3990972	total: 1.15s	remaining: 17s
318:	learn: 0.3990057	total: 1.16s	remaining: 17s
319:	learn: 0.3989665	total: 1.16s	remaining: 17s
320:	learn: 0.3989281	total: 1.17s	remaining: 17s
321:	learn: 0.3988418	total: 1.17s	remaining: 17s
322:	learn: 0.3987866	total: 1.18s	remaining: 17s
323:	learn: 0.3987239	total: 1.18s	remaining: 17s
324:	learn: 0.3986811	total: 1.18s	remaining: 17s
325:	learn: 0.3986527	total: 1.19s	remaining: 17s
326:	learn: 0.3985962	total: 1.19s	remaining: 17s
327:	learn: 0.3985607	total: 1.19s	remaining: 17s
328:	learn: 0.3985147	total: 1.2s	remaining: 17s
329:	learn: 0.3984923	total: 1.2s	remaining: 17s
330:	learn: 0.3984495	total: 1.2s	remaining: 17s
331:	learn: 0.3983811	total: 1.21s	remaining: 17s
332:	learn: 0.3983185	total: 1.21s	remaining: 17s
333:	learn: 0.3982789	total: 1.22s	remaining: 17s
334:	learn: 0.3982567	total: 1.22s	remaining: 17s
335:	learn: 0.3982444	total: 1.22s	remaining: 17s
336:	learn: 0.3982129	total: 1.23s	remaining: 17s
337:	learn: 0.3981510	total: 1.23s	remaining: 17s
338:	learn: 0.3981156	total: 1.24s	remaining: 17s
339:	learn: 0.3980681	total: 1.24s	remaining: 17s
340:	learn: 0.3980186	total: 1.24s	remaining: 17s
341:	learn: 0.3979635	total: 1.24s	remaining: 17s
342:	learn: 0.3979066	total: 1.25s	remaining: 16.9s
343:	learn: 0.3978433	total: 1.25s	remaining: 16.9s
344:	learn: 0.3977956	total: 1.25s	remaining: 16.9s
345:	learn: 0.3977390	total: 1.26s	remaining: 16.9s
346:	learn: 0.3976796	total: 1.26s	remaining: 16.9s
347:	learn: 0.3976405	total: 1.26s	remaining: 16.9s
348:	learn: 0.3976211	total: 1.27s	remaining: 16.9s
349:	learn: 0.3975606	total: 1.27s	remaining: 16.9s
350:	learn: 0.3975336	total: 1.27s	remaining: 16.9s
351:	learn: 0.3974763	total: 1.28s	remaining: 16.9s
352:	learn: 0.3974561	total: 1.28s	remaining: 16.9s
353:	learn: 0.3974046	total: 1.28s	remaining: 16.8s
354:	learn: 0.3973542	total: 1.29s	remaining: 16.8s
355:	learn: 0.3972991	total: 1.29s	remaining: 16.8s
356:	learn: 0.3972492	total: 1.29s	remaining: 16.8s
357:	learn: 0.3972109	total: 1.29s	remaining: 16.8s
358:	learn: 0.3971764	total: 1.3s	remaining: 16.8s
359:	learn: 0.3971405	total: 1.3s	remaining: 16.8s
360:	learn: 0.3971137	total: 1.31s	remaining: 16.8s
361:	learn: 0.3970348	total: 1.31s	remaining: 16.8s
362:	learn: 0.3969898	total: 1.32s	remaining: 16.8s
363:	learn: 0.3969620	total: 1.32s	remaining: 16.8s
364:	learn: 0.3969266	total: 1.32s	remaining: 16.8s
365:	learn: 0.3968579	total: 1.33s	remaining: 16.8s
366:	learn: 0.3968198	total: 1.33s	remaining: 16.8s
367:	learn: 0.3967728	total: 1.33s	remaining: 16.8s
368:	learn: 0.3967286	total: 1.34s	remaining: 16.8s
369:	learn: 0.3967027	total: 1.34s	remaining: 16.8s
370:	learn: 0.3966600	total: 1.35s	remaining: 16.8s
371:	learn: 0.3966312	total: 1.35s	remaining: 16.8s
372:	learn: 0.3965363	total: 1.35s	remaining: 16.8s
373:	learn: 0.3964574	total: 1.35s	remaining: 16.8s
374:	learn: 0.3963850	total: 1.36s	remaining: 16.8s
375:	learn: 0.3963031	total: 1.36s	remaining: 16.8s
376:	learn: 0.3962332	total: 1.36s	remaining: 16.7s
377:	learn: 0.3961889	total: 1.37s	remaining: 16.7s
378:	learn: 0.3961142	total: 1.37s	remaining: 16.7s
379:	learn: 0.3960524	total: 1.37s	remaining: 16.7s
380:	learn: 0.3960076	total: 1.38s	remaining: 16.7s
381:	learn: 0.3959567	total: 1.38s	remaining: 16.7s
382:	learn: 0.3959080	total: 1.39s	remaining: 16.7s
383:	learn: 0.3958902	total: 1.39s	remaining: 16.7s
384:	learn: 0.3958586	total: 1.4s	remaining: 16.7s
385:	learn: 0.3958262	total: 1.4s	remaining: 16.7s
386:	learn: 0.3957700	total: 1.4s	remaining: 16.7s
387:	learn: 0.3956696	total: 1.41s	remaining: 16.7s

np.float64(0.7880724174653887)

In [62]:
# on the basis of all accuracy and confusion matrix i find that catboost give more accuary and balance model accuracy in train and test data

create pipeline

In [111]:
full_Pipeline = Pipeline([
    ("clean",preprocessing),
    ('model',CatBoostClassifier(iterations=5000,learning_rate=0.05,depth=2,l2_leaf_reg =3,random_state=42))
])

In [114]:
x_train_clean.columns.tolist()

['totalcharge__TotalCharges',
 'binary__gender',
 'binary__Partner',
 'binary__Dependents',
 'binary__PhoneService',
 'binary__OnlineSecurity',
 'binary__OnlineBackup',
 'binary__DeviceProtection',
 'binary__TechSupport',
 'binary__StreamingTV',
 'binary__StreamingMovies',
 'binary__PaperlessBilling',
 'nominal__MultipleLines_No',
 'nominal__MultipleLines_No phone service',
 'nominal__MultipleLines_Yes',
 'nominal__InternetService_DSL',
 'nominal__InternetService_Fiber optic',
 'nominal__InternetService_No',
 'nominal__Contract_Month-to-month',
 'nominal__Contract_One year',
 'nominal__Contract_Two year',
 'nominal__PaymentMethod_Bank transfer (automatic)',
 'nominal__PaymentMethod_Credit card (automatic)',
 'nominal__PaymentMethod_Electronic check',
 'nominal__PaymentMethod_Mailed check',
 'fixed__SeniorCitizen',
 'numeric_col__tenure',
 'numeric_col__MonthlyCharges']

In [115]:
x_train.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges']

In [116]:
full_Pipeline.fit(x_train,y_train)

0:	learn: 0.6652241	total: 5.78ms	remaining: 28.9s
1:	learn: 0.6394576	total: 11.1ms	remaining: 27.6s
2:	learn: 0.6175039	total: 15.4ms	remaining: 25.7s
3:	learn: 0.5977897	total: 19.8ms	remaining: 24.7s
4:	learn: 0.5840276	total: 24ms	remaining: 24s
5:	learn: 0.5691022	total: 28.6ms	remaining: 23.8s
6:	learn: 0.5574548	total: 33.1ms	remaining: 23.6s
7:	learn: 0.5469606	total: 37.3ms	remaining: 23.3s
8:	learn: 0.5353283	total: 43.2ms	remaining: 23.9s
9:	learn: 0.5264349	total: 47.8ms	remaining: 23.9s
10:	learn: 0.5186289	total: 52.7ms	remaining: 23.9s
11:	learn: 0.5103733	total: 57ms	remaining: 23.7s
12:	learn: 0.5026793	total: 61.4ms	remaining: 23.5s
13:	learn: 0.4972920	total: 65.6ms	remaining: 23.4s
14:	learn: 0.4920029	total: 69.5ms	remaining: 23.1s
15:	learn: 0.4875491	total: 73.8ms	remaining: 23s
16:	learn: 0.4823709	total: 77.9ms	remaining: 22.8s
17:	learn: 0.4783674	total: 82ms	remaining: 22.7s
18:	learn: 0.4747092	total: 86.1ms	remaining: 22.6s
19:	learn: 0.4716130	total: 90ms	remaining: 22.4s
20:	learn: 0.4670014	total: 94.2ms	remaining: 22.3s
21:	learn: 0.4634421	total: 98.8ms	remaining: 22.4s
22:	learn: 0.4601108	total: 104ms	remaining: 22.4s
23:	learn: 0.4569134	total: 108ms	remaining: 22.4s
24:	learn: 0.4547435	total: 112ms	remaining: 22.4s
25:	learn: 0.4530739	total: 117ms	remaining: 22.4s
26:	learn: 0.4515136	total: 121ms	remaining: 22.3s
27:	learn: 0.4493443	total: 127ms	remaining: 22.6s
28:	learn: 0.4478885	total: 131ms	remaining: 22.5s
29:	learn: 0.4464284	total: 136ms	remaining: 22.5s
30:	learn: 0.4444102	total: 140ms	remaining: 22.5s
31:	learn: 0.4423601	total: 145ms	remaining: 22.4s
32:	learn: 0.4404854	total: 149ms	remaining: 22.4s
33:	learn: 0.4395390	total: 154ms	remaining: 22.4s
34:	learn: 0.4379884	total: 158ms	remaining: 22.4s
35:	learn: 0.4365818	total: 162ms	remaining: 22.3s
36:	learn: 0.4353347	total: 166ms	remaining: 22.2s
37:	learn: 0.4345812	total: 170ms	remaining: 22.2s
38:	learn: 0.4337738	total: 174ms	remaining: 22.1s
39:	learn: 0.4330421	total: 178ms	remaining: 22.1s
40:	learn: 0.4323116	total: 183ms	remaining: 22.1s
41:	learn: 0.4314906	total: 187ms	remaining: 22.1s
42:	learn: 0.4308232	total: 192ms	remaining: 22.1s
43:	learn: 0.4300954	total: 195ms	remaining: 22s
44:	learn: 0.4291383	total: 200ms	remaining: 22s
45:	learn: 0.4285324	total: 204ms	remaining: 21.9s
46:	learn: 0.4280400	total: 208ms	remaining: 21.9s
47:	learn: 0.4275206	total: 212ms	remaining: 21.9s
48:	learn: 0.4268663	total: 217ms	remaining: 21.9s
49:	learn: 0.4263720	total: 221ms	remaining: 21.9s
50:	learn: 0.4258562	total: 225ms	remaining: 21.8s
51:	learn: 0.4254055	total: 232ms	remaining: 22s
52:	learn: 0.4243535	total: 236ms	remaining: 22s
53:	learn: 0.4236769	total: 240ms	remaining: 22s
54:	learn: 0.4228962	total: 244ms	remaining: 21.9s
55:	learn: 0.4223924	total: 248ms	remaining: 21.9s
56:	learn: 0.4220472	total: 253ms	remaining: 22s
57:	learn: 0.4217615	total: 257ms	remaining: 21.9s
58:	learn: 0.4212906	total: 262ms	remaining: 21.9s
59:	learn: 0.4209123	total: 266ms	remaining: 21.9s
60:	learn: 0.4206543	total: 270ms	remaining: 21.8s
61:	learn: 0.4203727	total: 273ms	remaining: 21.8s
62:	learn: 0.4200713	total: 277ms	remaining: 21.7s
63:	learn: 0.4193612	total: 281ms	remaining: 21.7s
64:	learn: 0.4190146	total: 286ms	remaining: 21.7s
65:	learn: 0.4186283	total: 289ms	remaining: 21.6s
66:	learn: 0.4181656	total: 294ms	remaining: 21.6s
67:	learn: 0.4179051	total: 297ms	remaining: 21.6s
68:	learn: 0.4177244	total: 301ms	remaining: 21.5s
69:	learn: 0.4170910	total: 307ms	remaining: 21.6s
70:	learn: 0.4169599	total: 311ms	remaining: 21.6s
71:	learn: 0.4166477	total: 315ms	remaining: 21.6s
72:	learn: 0.4163840	total: 320ms	remaining: 21.6s
73:	learn: 0.4161549	total: 324ms	remaining: 21.6s
74:	learn: 0.4159481	total: 328ms	remaining: 21.5s
75:	learn: 0.4153835	total: 332ms	remaining: 21.5s
76:	learn: 0.4151211	total: 337ms	remaining: 21.5s
77:	learn: 0.4148352	total: 340ms	remaining: 21.5s
78:	learn: 0.4146303	total: 345ms	remaining: 21.5s
79:	learn: 0.4143773	total: 348ms	remaining: 21.4s
80:	learn: 0.4141744	total: 353ms	remaining: 21.4s
81:	learn: 0.4139208	total: 357ms	remaining: 21.4s
82:	learn: 0.4137497	total: 361ms	remaining: 21.4s
83:	learn: 0.4133246	total: 365ms	remaining: 21.4s
84:	learn: 0.4131050	total: 370ms	remaining: 21.4s
85:	learn: 0.4128523	total: 373ms	remaining: 21.3s
86:	learn: 0.4126541	total: 377ms	remaining: 21.3s
87:	learn: 0.4124892	total: 381ms	remaining: 21.3s
88:	learn: 0.4123824	total: 384ms	remaining: 21.2s
89:	learn: 0.4120328	total: 389ms	remaining: 21.2s
90:	learn: 0.4118616	total: 393ms	remaining: 21.2s
91:	learn: 0.4116959	total: 397ms	remaining: 21.2s
92:	learn: 0.4114496	total: 401ms	remaining: 21.2s
93:	learn: 0.4112055	total: 406ms	remaining: 21.2s
94:	learn: 0.4110505	total: 409ms	remaining: 21.1s
95:	learn: 0.4107646	total: 414ms	remaining: 21.2s
96:	learn: 0.4106047	total: 418ms	remaining: 21.1s
97:	learn: 0.4105039	total: 423ms	remaining: 21.2s
98:	learn: 0.4103349	total: 427ms	remaining: 21.1s
99:	learn: 0.4101632	total: 431ms	remaining: 21.1s
100:	learn: 0.4100352	total: 436ms	remaining: 21.2s
101:	learn: 0.4098944	total: 441ms	remaining: 21.2s
102:	learn: 0.4097498	total: 448ms	remaining: 21.3s
103:	learn: 0.4096485	total: 453ms	remaining: 21.3s
104:	learn: 0.4095074	total: 458ms	remaining: 21.4s
105:	learn: 0.4093657	total: 462ms	remaining: 21.3s
106:	learn: 0.4092501	total: 467ms	remaining: 21.4s
107:	learn: 0.4089830	total: 472ms	remaining: 21.4s
108:	learn: 0.4089005	total: 477ms	remaining: 21.4s
109:	learn: 0.4088220	total: 483ms	remaining: 21.5s
110:	learn: 0.4086964	total: 487ms	remaining: 21.5s
111:	learn: 0.4085708	total: 492ms	remaining: 21.5s
112:	learn: 0.4084950	total: 497ms	remaining: 21.5s
113:	learn: 0.4082822	total: 502ms	remaining: 21.5s
114:	learn: 0.4081677	total: 506ms	remaining: 21.5s
115:	learn: 0.4081014	total: 510ms	remaining: 21.5s
116:	learn: 0.4080169	total: 514ms	remaining: 21.4s
117:	learn: 0.4079540	total: 519ms	remaining: 21.5s
118:	learn: 0.4078308	total: 523ms	remaining: 21.5s
119:	learn: 0.4078114	total: 529ms	remaining: 21.5s
120:	learn: 0.4077702	total: 533ms	remaining: 21.5s
121:	learn: 0.4077045	total: 538ms	remaining: 21.5s
122:	learn: 0.4075898	total: 545ms	remaining: 21.6s
123:	learn: 0.4073417	total: 552ms	remaining: 21.7s
124:	learn: 0.4071394	total: 558ms	remaining: 21.8s
125:	learn: 0.4070991	total: 562ms	remaining: 21.7s
126:	learn: 0.4070684	total: 567ms	remaining: 21.7s
127:	learn: 0.4068876	total: 572ms	remaining: 21.8s
128:	learn: 0.4068235	total: 576ms	remaining: 21.8s
129:	learn: 0.4067817	total: 581ms	remaining: 21.8s
130:	learn: 0.4067379	total: 586ms	remaining: 21.8s
131:	learn: 0.4067010	total: 591ms	remaining: 21.8s
132:	learn: 0.4065568	total: 595ms	remaining: 21.8s
133:	learn: 0.4065174	total: 599ms	remaining: 21.8s
134:	learn: 0.4064311	total: 603ms	remaining: 21.7s
135:	learn: 0.4063418	total: 606ms	remaining: 21.7s
136:	learn: 0.4062446	total: 611ms	remaining: 21.7s
137:	learn: 0.4061708	total: 615ms	remaining: 21.7s
138:	learn: 0.4061471	total: 619ms	remaining: 21.6s
139:	learn: 0.4060979	total: 622ms	remaining: 21.6s
140:	learn: 0.4059448	total: 627ms	remaining: 21.6s
141:	learn: 0.4059131	total: 631ms	remaining: 21.6s
142:	learn: 0.4058691	total: 635ms	remaining: 21.6s
143:	learn: 0.4058168	total: 639ms	remaining: 21.5s
144:	learn: 0.4057611	total: 643ms	remaining: 21.5s
145:	learn: 0.4057086	total: 647ms	remaining: 21.5s
146:	learn: 0.4056611	total: 653ms	remaining: 21.6s
147:	learn: 0.4055605	total: 659ms	remaining: 21.6s
148:	learn: 0.4054977	total: 664ms	remaining: 21.6s
149:	learn: 0.4054272	total: 668ms	remaining: 21.6s
150:	learn: 0.4053496	total: 673ms	remaining: 21.6s
151:	learn: 0.4052179	total: 678ms	remaining: 21.6s
152:	learn: 0.4051767	total: 682ms	remaining: 21.6s
153:	learn: 0.4051214	total: 686ms	remaining: 21.6s
154:	learn: 0.4050595	total: 691ms	remaining: 21.6s
155:	learn: 0.4050056	total: 697ms	remaining: 21.6s
156:	learn: 0.4049619	total: 701ms	remaining: 21.6s
157:	learn: 0.4048895	total: 705ms	remaining: 21.6s
158:	learn: 0.4048110	total: 709ms	remaining: 21.6s
159:	learn: 0.4047272	total: 714ms	remaining: 21.6s
160:	learn: 0.4046716	total: 719ms	remaining: 21.6s
161:	learn: 0.4046219	total: 725ms	remaining: 21.6s
162:	learn: 0.4045728	total: 729ms	remaining: 21.6s
163:	learn: 0.4044882	total: 733ms	remaining: 21.6s
164:	learn: 0.4044110	total: 740ms	remaining: 21.7s
165:	learn: 0.4043504	total: 743ms	remaining: 21.6s
166:	learn: 0.4042889	total: 749ms	remaining: 21.7s
167:	learn: 0.4042255	total: 753ms	remaining: 21.7s
168:	learn: 0.4041739	total: 757ms	remaining: 21.6s
169:	learn: 0.4040791	total: 761ms	remaining: 21.6s
170:	learn: 0.4040564	total: 765ms	remaining: 21.6s
171:	learn: 0.4039758	total: 771ms	remaining: 21.6s
172:	learn: 0.4039238	total: 775ms	remaining: 21.6s
173:	learn: 0.4038812	total: 779ms	remaining: 21.6s
174:	learn: 0.4038219	total: 783ms	remaining: 21.6s
175:	learn: 0.4037416	total: 787ms	remaining: 21.6s
176:	learn: 0.4036514	total: 791ms	remaining: 21.6s
177:	learn: 0.4036166	total: 795ms	remaining: 21.5s
178:	learn: 0.4034598	total: 800ms	remaining: 21.6s
179:	learn: 0.4034172	total: 804ms	remaining: 21.5s
180:	learn: 0.4033951	total: 810ms	remaining: 21.6s
181:	learn: 0.4033573	total: 814ms	remaining: 21.6s
182:	learn: 0.4032799	total: 819ms	remaining: 21.6s
183:	learn: 0.4032547	total: 823ms	remaining: 21.5s
184:	learn: 0.4031395	total: 827ms	remaining: 21.5s
185:	learn: 0.4030780	total: 832ms	remaining: 21.5s
186:	learn: 0.4029937	total: 836ms	remaining: 21.5s
187:	learn: 0.4029666	total: 840ms	remaining: 21.5s
188:	learn: 0.4029113	total: 844ms	remaining: 21.5s
189:	learn: 0.4028633	total: 849ms	remaining: 21.5s
190:	learn: 0.4027896	total: 853ms	remaining: 21.5s
191:	learn: 0.4027167	total: 857ms	remaining: 21.5s
192:	learn: 0.4026206	total: 862ms	remaining: 21.5s
193:	learn: 0.4025733	total: 866ms	remaining: 21.5s
194:	learn: 0.4025216	total: 871ms	remaining: 21.5s
195:	learn: 0.4024587	total: 875ms	remaining: 21.4s
196:	learn: 0.4023979	total: 880ms	remaining: 21.5s
197:	learn: 0.4023508	total: 884ms	remaining: 21.4s
198:	learn: 0.4022861	total: 888ms	remaining: 21.4s
199:	learn: 0.4022223	total: 892ms	remaining: 21.4s
200:	learn: 0.4021810	total: 896ms	remaining: 21.4s
201:	learn: 0.4021269	total: 901ms	remaining: 21.4s
202:	learn: 0.4020710	total: 906ms	remaining: 21.4s
203:	learn: 0.4020222	total: 910ms	remaining: 21.4s
204:	learn: 0.4019584	total: 915ms	remaining: 21.4s
205:	learn: 0.4018896	total: 920ms	remaining: 21.4s
206:	learn: 0.4018180	total: 924ms	remaining: 21.4s
207:	learn: 0.4017661	total: 928ms	remaining: 21.4s
208:	learn: 0.4017221	total: 932ms	remaining: 21.4s
209:	learn: 0.4016146	total: 937ms	remaining: 21.4s
210:	learn: 0.4015506	total: 940ms	remaining: 21.3s
211:	learn: 0.4014823	total: 945ms	remaining: 21.3s
212:	learn: 0.4014310	total: 949ms	remaining: 21.3s
213:	learn: 0.4013738	total: 954ms	remaining: 21.3s
214:	learn: 0.4012922	total: 960ms	remaining: 21.4s
215:	learn: 0.4012571	total: 964ms	remaining: 21.4s
216:	learn: 0.4012187	total: 969ms	remaining: 21.4s
217:	learn: 0.4011806	total: 973ms	remaining: 21.4s
218:	learn: 0.4010914	total: 978ms	remaining: 21.3s
219:	learn: 0.4010325	total: 982ms	remaining: 21.3s
220:	learn: 0.4009992	total: 986ms	remaining: 21.3s
221:	learn: 0.4009505	total: 990ms	remaining: 21.3s
222:	learn: 0.4008751	total: 993ms	remaining: 21.3s
223:	learn: 0.4008223	total: 997ms	remaining: 21.3s
224:	learn: 0.4007884	total: 1s	remaining: 21.2s
225:	learn: 0.4007577	total: 1s	remaining: 21.2s
226:	learn: 0.4007010	total: 1.01s	remaining: 21.2s
227:	learn: 0.4006551	total: 1.01s	remaining: 21.2s
228:	learn: 0.4006035	total: 1.02s	remaining: 21.2s
229:	learn: 0.4005589	total: 1.02s	remaining: 21.2s
230:	learn: 0.4005011	total: 1.02s	remaining: 21.2s
231:	learn: 0.4004375	total: 1.03s	remaining: 21.1s
232:	learn: 0.4003882	total: 1.03s	remaining: 21.1s
233:	learn: 0.4003374	total: 1.04s	remaining: 21.1s
234:	learn: 0.4002740	total: 1.04s	remaining: 21.1s
235:	learn: 0.4002433	total: 1.04s	remaining: 21.1s
236:	learn: 0.4002121	total: 1.05s	remaining: 21.1s
237:	learn: 0.4001396	total: 1.05s	remaining: 21.1s
238:	learn: 0.4000742	total: 1.06s	remaining: 21.1s
239:	learn: 0.4000264	total: 1.06s	remaining: 21.1s
240:	learn: 0.3999808	total: 1.06s	remaining: 21s
241:	learn: 0.3999098	total: 1.07s	remaining: 21s
242:	learn: 0.3998755	total: 1.07s	remaining: 21s
243:	learn: 0.3998449	total: 1.08s	remaining: 21s
244:	learn: 0.3998015	total: 1.08s	remaining: 21s
245:	learn: 0.3997588	total: 1.08s	remaining: 21s
246:	learn: 0.3996868	total: 1.09s	remaining: 21s
247:	learn: 0.3996166	total: 1.09s	remaining: 21s
248:	learn: 0.3995903	total: 1.1s	remaining: 21s
249:	learn: 0.3995435	total: 1.1s	remaining: 21s
250:	learn: 0.3995086	total: 1.11s	remaining: 20.9s
251:	learn: 0.3994803	total: 1.11s	remaining: 20.9s
252:	learn: 0.3994081	total: 1.12s	remaining: 21s
253:	learn: 0.3993618	total: 1.12s	remaining: 20.9s
254:	learn: 0.3993182	total: 1.13s	remaining: 20.9s
255:	learn: 0.3992610	total: 1.13s	remaining: 20.9s
256:	learn: 0.3992059	total: 1.13s	remaining: 20.9s
257:	learn: 0.3991704	total: 1.14s	remaining: 20.9s
258:	learn: 0.3991411	total: 1.14s	remaining: 20.9s
259:	learn: 0.3991140	total: 1.15s	remaining: 20.9s
260:	learn: 0.3990732	total: 1.15s	remaining: 20.9s
261:	learn: 0.3990141	total: 1.15s	remaining: 20.9s
262:	learn: 0.3989542	total: 1.16s	remaining: 20.9s
263:	learn: 0.3989173	total: 1.16s	remaining: 20.8s
264:	learn: 0.3988585	total: 1.17s	remaining: 20.8s
265:	learn: 0.3988154	total: 1.17s	remaining: 20.8s
266:	learn: 0.3987727	total: 1.17s	remaining: 20.8s
267:	learn: 0.3987393	total: 1.18s	remaining: 20.8s
268:	learn: 0.3986773	total: 1.18s	remaining: 20.8s
269:	learn: 0.3986242	total: 1.19s	remaining: 20.8s
270:	learn: 0.3985852	total: 1.19s	remaining: 20.8s
271:	learn: 0.3985469	total: 1.19s	remaining: 20.7s
272:	learn: 0.3984935	total: 1.2s	remaining: 20.7s
273:	learn: 0.3984638	total: 1.2s	remaining: 20.7s
274:	learn: 0.3983827	total: 1.2s	remaining: 20.7s
275:	learn: 0.3983483	total: 1.21s	remaining: 20.7s
276:	learn: 0.3982639	total: 1.21s	remaining: 20.7s
277:	learn: 0.3982223	total: 1.22s	remaining: 20.7s
278:	learn: 0.3981940	total: 1.22s	remaining: 20.6s
279:	learn: 0.3981529	total: 1.22s	remaining: 20.6s
280:	learn: 0.3981149	total: 1.23s	remaining: 20.6s
281:	learn: 0.3980787	total: 1.23s	remaining: 20.6s
282:	learn: 0.3980486	total: 1.24s	remaining: 20.6s
283:	learn: 0.3980088	total: 1.24s	remaining: 20.6s
284:	learn: 0.3979713	total: 1.26s	remaining: 20.9s
285:	learn: 0.3979479	total: 1.27s	remaining: 20.9s
286:	learn: 0.3978978	total: 1.27s	remaining: 20.9s
287:	learn: 0.3978537	total: 1.28s	remaining: 20.9s
288:	learn: 0.3978268	total: 1.28s	remaining: 20.9s
289:	learn: 0.3977873	total: 1.29s	remaining: 20.9s
290:	learn: 0.3977627	total: 1.29s	remaining: 20.9s
291:	learn: 0.3977275	total: 1.29s	remaining: 20.9s
292:	learn: 0.3976571	total: 1.3s	remaining: 20.9s
293:	learn: 0.3976238	total: 1.3s	remaining: 20.9s
294:	learn: 0.3975883	total: 1.31s	remaining: 20.9s
295:	learn: 0.3975189	total: 1.31s	remaining: 20.9s
296:	learn: 0.3974868	total: 1.32s	remaining: 20.9s
297:	learn: 0.3974633	total: 1.32s	remaining: 20.9s
298:	learn: 0.3974266	total: 1.33s	remaining: 20.9s
299:	learn: 0.3974038	total: 1.33s	remaining: 20.9s
300:	learn: 0.3973565	total: 1.34s	remaining: 20.9s
301:	learn: 0.3973325	total: 1.34s	remaining: 20.9s
302:	learn: 0.3973008	total: 1.34s	remaining: 20.8s
303:	learn: 0.3972790	total: 1.35s	remaining: 20.8s
304:	learn: 0.3972052	total: 1.35s	remaining: 20.8s
305:	learn: 0.3971676	total: 1.36s	remaining: 20.8s
306:	learn: 0.3971308	total: 1.36s	remaining: 20.8s
307:	learn: 0.3970969	total: 1.36s	remaining: 20.8s
308:	learn: 0.3970772	total: 1.37s	remaining: 20.8s
309:	learn: 0.3970559	total: 1.37s	remaining: 20.8s
310:	learn: 0.3970263	total: 1.38s	remaining: 20.8s
311:	learn: 0.3969829	total: 1.38s	remaining: 20.8s
312:	learn: 0.3969351	total: 1.39s	remaining: 20.8s
313:	learn: 0.3969069	total: 1.39s	remaining: 20.8s
314:	learn: 0.3968734	total: 1.4s	remaining: 20.8s
315:	learn: 0.3968300	total: 1.4s	remaining: 20.7s
316:	learn: 0.3967967	total: 1.4s	remaining: 20.7s
317:	learn: 0.3967563	total: 1.41s	remaining: 20.7s
318:	learn: 0.3966975	total: 1.41s	remaining: 20.7s
319:	learn: 0.3966596	total: 1.42s	remaining: 20.7s
320:	learn: 0.3966298	total: 1.42s	remaining: 20.7s
321:	learn: 0.3965594	total: 1.43s	remaining: 20.7s
322:	learn: 0.3965410	total: 1.43s	remaining: 20.7s
323:	learn: 0.3965158	total: 1.43s	remaining: 20.7s
324:	learn: 0.3964820	total: 1.44s	remaining: 20.7s
325:	learn: 0.3964588	total: 1.44s	remaining: 20.7s
326:	learn: 0.3964141	total: 1.45s	remaining: 20.7s
327:	learn: 0.3963417	total: 1.45s	remaining: 20.7s
328:	learn: 0.3963054	total: 1.46s	remaining: 20.7s
329:	learn: 0.3962512	total: 1.46s	remaining: 20.7s
330:	learn: 0.3962236	total: 1.46s	remaining: 20.7s
331:	learn: 0.3961895	total: 1.47s	remaining: 20.6s
332:	learn: 0.3961222	total: 1.47s	remaining: 20.6s
333:	learn: 0.3960978	total: 1.48s	remaining: 20.7s
334:	learn: 0.3960626	total: 1.48s	remaining: 20.6s
335:	learn: 0.3960409	total: 1.49s	remaining: 20.7s
336:	learn: 0.3959818	total: 1.49s	remaining: 20.6s
337:	learn: 0.3959170	total: 1.5s	remaining: 20.6s
338:	learn: 0.3958942	total: 1.5s	remaining: 20.6s
339:	learn: 0.3958738	total: 1.51s	remaining: 20.7s
340:	learn: 0.3958109	total: 1.51s	remaining: 20.7s
341:	learn: 0.3957514	total: 1.52s	remaining: 20.7s
342:	learn: 0.3957264	total: 1.52s	remaining: 20.7s
343:	learn: 0.3956452	total: 1.53s	remaining: 20.7s
344:	learn: 0.3956353	total: 1.53s	remaining: 20.7s
345:	learn: 0.3955370	total: 1.54s	remaining: 20.7s
346:	learn: 0.3955296	total: 1.54s	remaining: 20.7s
347:	learn: 0.3954692	total: 1.55s	remaining: 20.7s
348:	learn: 0.3954186	total: 1.56s	remaining: 20.7s
349:	learn: 0.3953726	total: 1.56s	remaining: 20.7s
350:	learn: 0.3953182	total: 1.56s	remaining: 20.7s
351:	learn: 0.3953094	total: 1.58s	remaining: 20.8s
352:	learn: 0.3952477	total: 1.58s	remaining: 20.8s
353:	learn: 0.3951988	total: 1.59s	remaining: 20.8s
354:	learn: 0.3951427	total: 1.59s	remaining: 20.8s
355:	learn: 0.3951221	total: 1.59s	remaining: 20.8s
356:	learn: 0.3950801	total: 1.6s	remaining: 20.8s
357:	learn: 0.3950524	total: 1.61s	remaining: 20.8s
358:	learn: 0.3950315	total: 1.61s	remaining: 20.8s
359:	learn: 0.3949770	total: 1.62s	remaining: 20.8s
360:	learn: 0.3949558	total: 1.62s	remaining: 20.9s
361:	learn: 0.3949375	total: 1.63s	remaining: 20.9s
362:	learn: 0.3949147	total: 1.63s	remaining: 20.9s
363:	learn: 0.3948733	total: 1.64s	remaining: 20.9s
364:	learn: 0.3948430	total: 1.64s	remaining: 20.9s
365:	learn: 0.3948090	total: 1.65s	remaining: 20.9s
366:	learn: 0.3947887	total: 1.65s	remaining: 20.9s
367:	learn: 0.3947592	total: 1.66s	remaining: 20.9s
368:	learn: 0.3947164	total: 1.67s	remaining: 20.9s
369:	learn: 0.3946669	total: 1.67s	remaining: 20.9s
370:	learn: 0.3946582	total: 1.68s	remaining: 20.9s
371:	learn: 0.3946408	total: 1.68s	remaining: 20.9s
372:	learn: 0.3945885	total: 1.68s	remaining: 20.9s
373:	learn: 0.3945512	total: 1.69s	remaining: 20.9s
374:	learn: 0.3944947	total: 1.69s	remaining: 20.9s
375:	learn: 0.3944689	total: 1.7s	remaining: 20.9s
376:	learn: 0.3944378	total: 1.7s	remaining: 20.9s
377:	learn: 0.3944169	total: 1.71s	remaining: 20.9s
378:	learn: 0.3943942	total: 1.72s	remaining: 20.9s
379:	learn: 0.3943429	total: 1.72s	remaining: 20.9s
380:	learn: 0.3943217	total: 1.73s	remaining: 20.9s
381:	learn: 0.3942636	total: 1.73s	remaining: 20.9s
382:	learn: 0.3942394	total: 1.74s	remaining: 20.9s
383:	learn: 0.3942132	total: 1.74s	remaining: 21s
384:	learn: 0.3941284	total: 1.75s	remaining: 21s
385:	learn: 0.3941008	total: 1.75s	remaining: 21s
386:	learn: 0.3940806	total: 1.76s	remaining: 21s

Pipeline(steps=[('clean',
                 ColumnTransformer(transformers=[('totalcharge',
                                                  Pipeline(steps=[('convert',
                                                                   FunctionTransformer(feature_names_out=<function get_new_num_names at 0x000001CFCDC17060>,
                                                                                       func=<function cat_to_num at 0x000001CFCDC17420>)),
                                                                  ('imput',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['TotalCharges']),
                                                 ('binary',
                                                  Pipeline(steps=[...
                                                   'PaymentMethod']),
                                                 ('fixed',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent'))]),
                                                  ['SeniorCitizen']),
                                                 ('numeric_col',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tenure',
                                                   'MonthlyCharges'])])),
                ('model',
                 CatBoostClassifier(depth=2, iterations=5000, l2_leaf_reg=3, learning_rate=0.05, random_state=42))])

save file model

In [121]:
file_name_create = f"Customer_churn_ML_model.pkl"
folder_path = os.path.join(ML_MODELS,file_name_create)
folder_path

'c:\\Users\\hamen\\OneDrive\\Desktop\\ml_project\\Telco_Customer_Churn_ML_Project\\ML_Pipelines\\Customer_churn_ML_model.pkl'

In [122]:
joblib.dump(full_Pipeline,folder_path)

['c:\\Users\\hamen\\OneDrive\\Desktop\\ml_project\\Telco_Customer_Churn_ML_Project\\ML_Pipelines\\Customer_churn_ML_model.pkl']